# python base image in the container from Docker Hub
FROM python:3.8.12-buster

# copy files to the /app folder in the container
COPY .streamlit/. /app/.streamlit/.
COPY requirements.txt /app/requirements.txt
COPY app.py /app/app.py

RUN pip install -r /app/requirements.txt

EXPOSE 8504

# execute the command python main.py (in the WORKDIR) to start the app
CMD ["streamlit", "run", "app/app.py", "--server.port", "8504"]
